### ISSUE TITLE
Template and box corners

### ISSUE THREAD

**Issue by Cabalist** [Deftaudio/MacroPot#2]
Hey there,

I thought I should just give you (and future kit builders) a heads up that the drilling for the template can be quite difficult.   I've made a a mess of the provided box and wanted to document how.

Currently the printed template has the four threaded holes to hold the acrylic top in the corners of the aluminum box.  The box I received also had  4 preexisting threaded holes in the other side.   The interfered with the template and caused the drill bit to shift.   I doubt this would have been a problem with a small drill press but I was drilling these by hand.   

I think this could be fixed by moving the acrylic supports in from the corners so that they don't overlap the existing holes.   It would also probably be worthwhile to mark some median lines on the template to ensure alignment. 

If others are looking for this box it is a 1590A and available from all the usual places.  There are a bunch of pre-painted ones out there as well.  :) 
 
<img width="538" alt="Screen Shot 2019-10-04 at 9 43 36 AM" src="https://user-images.githubusercontent.com/828557/66224721-76d4a200-e68b-11e9-95f3-8cc8d1825ac2.png">
<img width="610" alt="Screen Shot 2019-10-04 at 9 43 21 AM" src="https://user-images.githubusercontent.com/828557/66224722-76d4a200-e68b-11e9-8939-4abc602ccc54.png">

**Comment by Deftaudio** [comment]
Thank you for a heads up on that. 1590A is in the BOM list, just right here: https://docs.google.com/spreadsheets/d/15D16pYKxWzvwlihMUm6H49rWIW-DiubtF_ozgL0KMLI/edit?usp=sharing
Might be good idea to put painted versions too.
But the main problem, that's seen on the photos too is rounded corners and all lines which vary from one unit to another. I'd expect because they were polished manually. That's why I had to reduce the size of the acrylic panel, so it goes on the flat surface only. As a result of that corner holes moved slightly to the center which made them offset to the enclosure back holes. If I move acrylic holes to match enclosure holes, I afraid it will be to thin on the corner which is not good either. Anyway, experiment, let me know and propose any changes that can make it better.

**Comment by Cabalist** [comment]
No worries.   I didn't see that number on the BOM just an eBay listing.  :) 

I think you are right that the there isn't a way to line up with the existing corner holes but I think if the holes are brought in closer to the center by another 5 or 6mm they won't interfere with the supports.

**Comment by Deftaudio** [comment]
Closer to the center? This is a nice idea. Then the only problem is the length of the screws, so they won't interfere with a PCB then.
